#!/usr/bin/env python3
"""Fair-use audit for the launch legal pass.

Aggregates every guidance quote across term pages per source org:
quote count, total words quoted, longest quote, pages citing. Flags:
  F1  any single quote > 50 words (should be impossible post-W2 lint)
  F2  aggregate words quoted from one org > AGG_WARN words (heavy use
      of a single source deserves a human look)
  F3  source page host_posture says host-publicly for an org whose
      source is live (guardrail: never host an active org's content)
  F4  archive file present under site/public/ (would mean we're
      actually serving a mirror publicly)

Output: notes/fair-use-audit.md
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TERMS = os.path.join(ROOT, "site/src/content/terms")
SOURCES = os.path.join(ROOT, "site/src/content/sources")
OUT = os.path.join(ROOT, "notes/fair-use-audit.md")
AGG_WARN = 400  # words quoted in aggregate from one org before flagging

quote_re = re.compile(r'^\s+- org: "(.*)"\n(?:.+\n)*?\s+quote: "(.*)"', re.M)


def parse_entries(text):
    """Yield (org, org_slug, quote) for each guidance entry."""
    entries = []
    cur = {}
    in_guidance = False
    for line in text.splitlines():
        if line.startswith("guidance:"):
            in_guidance = True
            continue
        if in_guidance and re.match(r"^[a-z_]+:", line):  # next top-level key
            break
        if not in_guidance:
            continue
        m = re.match(r'\s+- org: "(.*)"', line)
        if m:
            if cur.get("org") and cur.get("quote"):
                entries.append(cur)
            cur = {"org": m.group(1)}
            continue
        for key in ("org_slug", "quote"):
            m = re.match(rf'\s+{key}: "(.*)"', line)
            if m:
                cur[key] = m.group(1)
    if cur.get("org") and cur.get("quote"):
        entries.append(cur)
    return entries


def words(s):
    s = re.sub(r"[…\\]", " ", s)
    return len([w for w in s.split() if w])


orgs = {}
f1 = []
for path in sorted(glob.glob(f"{TERMS}/*.md")):
    page = os.path.basename(path)[:-3]
    for e in parse_entries(open(path).read()):
        slug = e.get("org_slug", e["org"])
        o = orgs.setdefault(slug, {"org": e["org"], "quotes": 0, "words": 0,
                                   "longest": 0, "longest_page": "", "pages": set()})
        w = words(e["quote"])
        o["quotes"] += 1
        o["words"] += w
        o["pages"].add(page)
        if w > o["longest"]:
            o["longest"], o["longest_page"] = w, page
        if w > 50:
            f1.append(f"{page}: {slug} quote is {w} words")

# posture checks
f3, f4 = [], []
for path in sorted(glob.glob(f"{SOURCES}/*.md")):
    text = open(path).read()
    posture = re.search(r'host_posture: "(.*)"', text)
    live = re.search(r'live_status: "(.*)"', text)
    if posture and posture.group(1) == "host-publicly" and live and live.group(1) == "live":
        f3.append(os.path.basename(path))

for path in glob.glob(os.path.join(ROOT, "site/public/**/*"), recursive=True):
    base = os.path.basename(path).lower()
    if base.endswith((".pdf",)) and "source" in path.lower():
        f4.append(os.path.relpath(path, ROOT))

rows = sorted(orgs.items(), key=lambda kv: -kv[1]["words"])
f2 = [(slug, o) for slug, o in rows if o["words"] > AGG_WARN]

with open(OUT, "w") as f:
    f.write("# Fair-use audit\n\n")
    f.write(f"Generated by `scripts/fair-use-audit.py`. Aggregate-words warn threshold: {AGG_WARN}.\n\n")
    f.write("## Flags\n\n")
    if not (f1 or f2 or f3 or f4):
        f.write("None. All quotes ≤50 words, no org over the aggregate threshold, "
                "no public hosting of live orgs' content.\n\n")
    for x in f1:
        f.write(f"- **F1 over-length quote** {x}\n")
    for slug, o in f2:
        f.write(f"- **F2 heavy aggregate** {o['org']} ({slug}): {o['words']} words "
                f"across {o['quotes']} quotes on {len(o['pages'])} pages\n")
    for x in f3:
        f.write(f"- **F3 host-publicly on live org** {x}\n")
    for x in f4:
        f.write(f"- **F4 archive served publicly** {x}\n")
    f.write("\n## Per-org aggregate (descending by words quoted)\n\n")
    for slug, o in rows:
        f.write(f"- **{o['org']}** (`{slug}`): {o['quotes']} quotes, "
                f"{o['words']} words total, longest {o['longest']}w "
                f"(on {o['longest_page']}), {len(o['pages'])} pages\n")

flags = len(f1) + len(f2) + len(f3) + len(f4)
print(f"fair-use-audit: {sum(o['quotes'] for _, o in rows)} quotes, "
      f"{len(rows)} orgs, {flags} flags → {os.path.relpath(OUT, ROOT)}")
sys.exit(0)
